"""add users and book tables

Revision ID: d1f04995879e
Revises: 
Create Date: 2020-11-05 02:43:34.496076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1f04995879e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION "uuid-ossp";')
    op.create_table('books_meta',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('books_exemplars',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('meta_id', postgresql.UUID(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['books_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_exemplars')
    op.drop_table('user')
    op.drop_table('books_meta')
    # ### end Alembic commands ###
